name: Book

on:
  push:
    branches:
      - master

jobs:
  book:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download mdBook
        uses: Legion2/download-release-action@v2.1.0
        with:
          repository: barsoosayque/mdBook
          tag: 'symlinks-patch'
          file: mdbook.tar.gz

      - name: Build book
        run: ./mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/
